### ISSUE TITLE
[FEAT] Create a README file

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/.github#2]
See 
* https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/
* https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

**Tasks**
- [x] baseline of the project
- [x] link to the website
- [x] hacktoberfest image
- [x] contributing cheat sheet: #3
